# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa62302150db347107aab983d0acd7019564e3e98fc86479903bd46bc607914b69b84bea63678eebb2f997f38c276928d0480dde286138f391a8a7236a80f439

test:
  secret_key_base: 74680ab3af2af25a3d6d7f83839c395a1bc73656e2e84a279f4ccc3dfafa073e8f0d136171853403811872c67f078c9d34b3f7756424553a647d92ed2d006487

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
